### PR TITLE
fix[close #356]: Block not removed when canceling update

### LINKED ISSUE #356: Block not removed when canceling update
When upgrading with abroot, and pressing ctrl + c the lock is not removed and a restart is required

### PR DESCRIPTION
**Pull request by mirkobrombin**
This will ensure the upgrade lock file gets removed if no other abroot instances are running.

Tested locally, using `abroot config-editor` to start a new process, then `abroot upgrade --dry-run` on a new terminal:
```
  ERROR   upgrades are locked, another is running
```
while closing the first process:
```
  ERROR   no update available
```

### CODE REVIEW

File: core/system.go [hunk 1]
```diff
@@ -949,3 +957,40 @@ func (s *ABSystem) RemoveStageFile() error {
...
+	procs, err := os.ReadDir("/proc")
+	if err != nil {
+		return false
+	}
+
+	for _, file := range procs {
+		if file.IsDir() {
+			if _, err := strconv.Atoi(file.Name()); err == nil {
+				cmdline, err := os.ReadFile("/proc/" + file.Name() + "/cmdline")
+				if err == nil && strings.Contains(string(cmdline), "abroot") {
```
Comment (axtloss) [inline core/system.go:974]: This should also check if the `/proc/<pid>/exe` symlink points to an abroot executable, like [busybox pidof](https://github.com/brgl/busybox/blob/master/libbb/find_pid_by_name.c#L91-L94) and [procps-ng](https://gitlab.com/procps-ng/procps/-/blob/master/src/pidof.c?ref_type=heads#L199) do

**Review by axtloss — APPROVED** [review]
